### ISSUE TITLE
Problemas al guardar las opciones de backup

### ISSUE THREAD

**Issue by fperezgaliana** [soltecsis/fwcloud-api#28]
Estoy haciendo pruebas para la funcionalidad de las copias de seguridad y he detectado los siguientes problemas:

--- Parece que la expresión regular que verifica los días no permite listas de días separados por comas en el campo del día de semana:

![imagen](https://user-images.githubusercontent.com/28951240/74135878-5e523680-4bed-11ea-84ef-4fc2f0d36f29.png)

--- Asímismo, cuando sí que se acepta la expresión regular, hay un problema con el nombre del fichero de configuración:

![imagen](https://user-images.githubusercontent.com/28951240/74135967-8fcb0200-4bed-11ea-83ae-a3ccb4e56fe2.png)

**Comment by fperezgaliana** [comment]
He encontrado la siguiente expresión regular que parece que cumple con todos los requisitos de las cadenas de cron:

https://regex101.com/r/sX0qR3/1

**Comment by fperezgaliana** [comment]
He visto que el backend ya es más permisivo con cadenas Cron. Sin embargo, el módulo `CronTime` no puede parsearlas. Por ejemplo, para la cadena "0 0 */3 * * 1,3,7" se produce el siguiente fallo:

> stack:"Error: Field (1,3,7) value is out of range\n    at /home/felip/Documentos/SOLTECSIS/proyectos/FWCloud.nodeapi/node_modules/cron/lib/cron.js:476:14\n    at String.replace (<anonymous>)\n    at CronTime._parseField (/home/felip/Documentos/SOLTECSIS/proyectos/FWCloud.nodeapi/node_modules/cron/lib/cron.js:456:19)\n    at CronTime._parse (/home/felip/Documentos/SOLTECSIS/proyectos/FWCloud.nodeapi/node_modules/cron/lib/cron.js:429:10)\n    at new CronTime (/home/felip/Documentos/SOLTECSIS/proyectos/FWCloud.nodeapi/node_modules/cron/lib/cron.js:46:9)\n    at /home/felip/Documentos/SOLTECSIS/proyectos/FWCloud.nodeapi/models/backup/backup.js:182:20\n    at new Promise (<anonymous>)\n    at Object.backupModel.setSchedule (/home/felip/Documentos/SOLTECSIS/proyectos/FWCloud.nodeapi/models/backup/backup.js:177:9)\n    at /home/felip/Documentos/SOLTECSIS/proyectos/FWCloud.nodeapi/routes/backup/backup.js:188:21\n    at Layer.handle [as handle_request] (/home/felip/Documentos/SOLTECSIS/proyectos/FWCloud.nodeapi/node_modules/express/l...

El fallo se da en el método `setSchedule` del controlador `backup.js`.

**Comment by cmunyoz** [comment]
Hay que adaptarse a lo que soporte el módulo npm.
[...]
Cron Ranges
When specifying your cron values you'll need to make sure that your values fall within the ranges. For instance, some cron's use a 0-7 range for the day of week where both 0 and 7 represent Sunday. We do not. And that is an optimisation.

Seconds: 0-59
Minutes: 0-59
Hours: 0-23
Day of Month: 1-31
Months: 0-11 (Jan-Dec)
Day of Week: 0-6 (Sun-Sat)
[...]

Fíjate en lo que permite, no se puede indicar 7 en el día de la semana, tiene que ser de 0 a 6.
He dejado comentada la antigua expresión regular. Mira a ver la que sea más adecuada para cubrir lo soportado por el módulo npm de cron.

**Comment by fperezgaliana** [comment]
He adaptado el código para el formato soportado por el módulo, por lo que ya funciona correctamente.
