### ISSUE TITLE
ERROR: Proxing request

### ISSUE THREAD

**Issue by ukrolelo** [soltecsis/fwcloud-api#406]
Hey guyz :>
I have been playing with tower9/hostblock
And when it added the iptables drop rules from abuseipdb i wanted to try and see the rules in gui.
On import there is an error
"\"ERROR: Proxing request: /iptables-save/import?channel_id=b688c871-84ee-42c9-8535-90471c1b92df\""
https://drive.google.com/file/d/1w_ONYw5SSHf5O09MZHMr2Jy7JSNIX4Aq/view?usp=sharing

So i stopped it
and now i cant delete the firewall

`Deletion error
Error checking cluster restrictions: {"message":"ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`fwcloud`.`policy_r`, CONSTRAINT `FK_751d26a7b9854e3e0cabca64393` FOREIGN KEY (`firewall`) REFERENCES `firewall` (`id`))","code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`fwcloud`.`policy_r`, CONSTRAINT `FK_751d26a7b9854e3e0cabca64393` FOREIGN KEY (`firewall`) REFERENCES `firewall` (`id`))","sqlState":"23000","index":0,"sql":"DELETE FROM firewall WHERE id=12 AND fwcloud=1","name":"QueryFailedError","query":"DELETE FROM firewall WHERE id=12 AND fwcloud=1","parameters":[]}`

`An error has occurred:
Error code 999999

{"message":"ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`fwcloud`.`policy_r__ipobj`, CONSTRAINT `FK_efbd20199d8093ec6d53564eabe` FOREIGN KEY (`rule`) REFERENCES `policy_r` (`id`))","code":"ER_ROW_IS_REFERENCED_2","errno":1451,"sqlMessage":"Cannot delete or update a parent row: a foreign key constraint fails (`fwcloud`.`policy_r__ipobj`, CONSTRAINT `FK_efbd20199d8093ec6d53564eabe` FOREIGN KEY (`rule`) REFERENCES `policy_r` (`id`))","sqlState":"23000","index":0,"sql":"DELETE FROM policy_r WHERE id=8803 AND firewall=12","name":"QueryFailedError","query":"DELETE FROM policy_r WHERE id=8803 AND firewall=12","parameters":[]}`

**Comment by ukrolelo** [comment]
When i tryed to delete rule by rule, it was working for a while and then the second error came.
I might broke the db :X

**Comment by ukrolelo** [comment]
Sure, Where can i send it privately to you?

**Comment by cmunyoz** [comment]
Send it to my attention using one of the contact e-mails of our website.

**Comment by ukrolelo** [comment]
oki

**Comment by ukrolelo** [comment]
sent on info@soltecsis.com

**Comment by cmunyoz** [comment]
Received.
We will let you know the results of our tests.

**Comment by ukrolelo** [comment]
So i was clicking around and found out that there is an option firewall Fix tree :) i clicked it and the broken firewall was gone. So now its fine. Nevertheless i have been stuck with thousands of IPs :)) the feature in new issue i posted. To make a multi select with shift+click to be able to delete all. Now i guess will try to do it through mysql dbeaver.

**Comment by cmunyoz** [comment]
The problem is that the `iptables-save` file to be imported has more that ten thousand lines, and it takes more time than the FWCloud-Websrv allows for an API request. For this reason this process generates a timeout error.

But if you pat attention you will see that the progress messages continues until the importation finishes.

For avoid the error you can increase the FWCloud-Websrv timeout adding this to the `.env` file into the directory `/opt/fwcloud/websrv`:
PROXY_TIMEOUT=1800000

By default the timeout is 10 minutes, but with this new value you increase it to 30 minutes.

**Comment by ukrolelo** [comment]
thank you, will put it there, just to double check 1800000 is in seconds? Should it be 1800 for 30min?

**Comment by cmunyoz** [comment]
It is in mili seconds.

**Comment by ukrolelo** [comment]
roger that, thank you!
