### ISSUE TITLE
multiselect object

### ISSUE THREAD

**Issue by ukrolelo** [soltecsis/fwcloud-api#411]
**Feature**
By accident i have 3000 ips in my object IP, it would be awesome to be able shift mouse click to select all of them and delete :>
Thx

**Comment by cmunyoz** [comment]
Thank you very much for the suggestion, we have added this to the milestone for our next release that will be published in June.

If you have a backup or snapshot previous to the creation of the thousands of IPs, you can restore it or rollback to the snapshot for remove this IPs meanwhile.

**Comment by ukrolelo** [comment]
I didn't make a fresh snapshot,i have been playing a lot with fwcloud back and forth with several servers.
Thank you! will wait till June <3
