### ISSUE TITLE
iptables suggestion feature

### ISSUE THREAD

**Issue by ukrolelo** [soltecsis/fwcloud-api#412]
I am googling for a week to find some top of the spec iptables rules to secure my server.
I would like to suggest if its interesting to have some shared db between clients where can people post their rules that they want to share for securing and it will be in one place and not over the internet.Maybe some special controlled forum thread idk?
I remember when i was trying out https://www.vuurmuur.org/
On load it would just put a lot of important rules to prevent against some basic attacks.But the app was glichy a bit so i removed it.
I think it would be awesome social feature :> Something like abuseipdb.com :>
If no, pls close this issue.

**Comment by cmunyoz** [comment]
Yes, it is a very interesting feature.
In fact we have open a new issue about this and the related post in our forum.
