### ISSUE TITLE
Add information fields on the routing routes and routing rules grid calls

### ISSUE THREAD

**Issue by fperezgaliana** [soltecsis/fwcloud-api#447]
To avoid extra API calls, the calls used to build the grid for the routing route tables and the routing policy need to return fields with the information of the objects that belong to different cluster or firewall to avoid missing this information when the policy is reloaded:

![imagen](https://user-images.githubusercontent.com/28951240/129568939-fc380441-fa99-408f-961e-7a1b1a0aedfb.png)

![imagen](https://user-images.githubusercontent.com/28951240/129568968-c90cf822-2ab6-42bb-8ebe-1c6fe47b567d.png)

**Comment by cmunyoz** [comment]
The backend was prepared for return these data, but there was a problem with the query.
It has been solved.
