### ISSUE TITLE
Can't delete non-empty routing tables

### ISSUE THREAD

**Issue by fperezgaliana** [soltecsis/fwcloud-api#456]
When trying to delete a routing table that has routes, we receive a constraints error:

```
message: "ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`fwcloud`.`route`, CONSTRAINT `FK_adba3a10de860d2b259cba3ebd3` FOREIGN KEY (`routing_table`) REFERENCES `routing_table` (`id`))"
response: "Internal Server Error"
```

**Comment by cmunyoz** [comment]
I have created a new firewall, created a routing table and one route into this routing table.
When I try to remove the routing table I get the error you can see in the next screenshot:
<img width="1440" alt="Captura de pantalla 2021-09-14 a las 10 37 22" src="https://user-images.githubusercontent.com/28894874/133224937-3ce910ce-493c-4a2e-aa3b-347a4600c0bb.png">

**Comment by fperezgaliana** [comment]
If you try to delete a routing table that is being used in a policy rule, you get the following error:

![imagen](https://user-images.githubusercontent.com/28951240/133240936-fa43b0d4-1c47-4bd9-92ce-1d9c3e6b4e59.png)

I'll add a more concise error message that tells that the table is being used and cannot be removed.

If you try to delete a routing table that isn't used anywhere, there's an API crash:

![imagen](https://user-images.githubusercontent.com/28951240/133241159-cceb40b3-2988-4a10-a27d-b8508ae300f5.png)

**Comment by fperezgaliana** [comment]
- [ ] When we try to delete a table that is used in a policy, the UI shows the following error:
![imagen](https://user-images.githubusercontent.com/28951240/133242671-48b31621-9b1e-47d2-aa14-92788db220d5.png)

**Comment by cmunyoz** [comment]
This message is incorrect.
A routing table can't contain routing rules, only routes.
The correct message would be:
"Cannot remove a routing table used in a routing rule"

**Comment by cmunyoz** [comment]
It doesn't go yet.

Follow these steps for reproduce the problem:
1. Create a new firewall.
2. Create a new routing table.
3. Add a new route.
4. Delete the routing table.
5. The next error is generated and I have to repair the tree for solve the problem.
<img width="1440" alt="Captura de pantalla 2021-09-15 a las 17 06 04" src="https://user-images.githubusercontent.com/28894874/133459390-6c2e1376-dc86-4153-8fd9-c9055f9a8c7c.png">
