### ISSUE TITLE
Incorrect validation of routing table number.

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-api#458]
The number of a routing table only can have values between 1 and 250, and the value 254.

The validation in the create and update DTOs is incorrect:
<img width="472" alt="Captura de pantalla 2021-08-18 a las 11 31 28" src="https://user-images.githubusercontent.com/28894874/129875237-876437e3-2c6c-443a-bf50-31a36e66035b.png">

**Comment by soltecsis-jurios** [comment]
Duplicate: #431
