### ISSUE TITLE
Fix "Where used" information for interfaces

### ISSUE THREAD

**Issue by fperezgaliana** [soltecsis/fwcloud-api#463]
I've detected that, for cluster interfaces, the "Where used" information is not correct:

![imagen](https://user-images.githubusercontent.com/28951240/130227988-f8133fa4-1e5f-4f2b-b9a2-984b8ec3229e.png)

As it's done in other dependency arrays, I would need the fields `cluster_id` and `cluster_name` to show it in the dialog.

**EDIT** To help locate the problem, this happens in the `InterfaceInFirewall` array.

**Comment by cmunyoz** [comment]
Solved!
