### ISSUE TITLE
Change the default value for 'show_action' for routing policy

### ISSUE THREAD

**Issue by fperezgaliana** [soltecsis/fwcloud-api#465]
I've realized that, the `policy_type` table has an incorrect value for the `show_action` column of the routing policies:

![imagen](https://user-images.githubusercontent.com/28951240/131690807-cadc25f2-2fd5-4cb2-b464-253c4a1584e7.png)

As you can see, the value is 1 when it should be 0, as the routing policy doesn't require the "Action" column on the grid.

**NOTE** To make it work while the column is changed, I've forced the value to be 0 for the routing policies.

**Comment by cmunyoz** [comment]
Solved but leave the code which forces this value to 0.
