### ISSUE TITLE
Errors in style and name changes of route groups and routing rules groups.

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-api#467]
- [x] It is possible to change the name of a routes group, but not of a routing rules group:

<img width="336" alt="Captura de pantalla 2021-09-03 a las 16 39 21" src="https://user-images.githubusercontent.com/28894874/132023458-c54e7efb-b050-4076-a4f3-4a956d4008ec.png">

- [x] It is possible to change the color of a route but not the color of a routing rule. The error is the same that we can see in the previous screenshot.
- [x] After changing the color of a routes group, if we reload, the color disappears. In the database remains, but it disappears  in the grid.

**Comment by fperezgaliana** [comment]
The error when changing the group name and style comes from the backend:

```
{"status":500,"response":"Internal Server Error","message":"Cannot read property 'length' of undefined","stack":["TypeError: 
Cannot read property 'length' of undefined","at RoutingGroupService.update 
(/home/felip/Documentos/SOLTECSIS/proyectos/fwcloud-api/dist/src/models/routing/routing-group/routing-group.service.js:51:32)"...
```
The change is done (if you refresh the policy you'll see the new name/style), so the error must be after performing the DB operation on the backend.

**Comment by fperezgaliana** [comment]
Everything works as expected, it's ready to close.
