### ISSUE TITLE
Error adding OpenVPN Prefixes to routes or routing rules of other firewall.

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-api#474]
If I try to add an OpenVPN Prefix **from other firewall** to the `To` position of a route or to the `From` position of a routing rule I get the next error:
<img width="1427" alt="Captura de pantalla 2021-09-14 a las 8 55 43" src="https://user-images.githubusercontent.com/28894874/133209944-408b75f8-86e7-48a1-97c0-8be6f654bf93.png">

This doesn't happens with OpenVPN objects.

**Comment by fperezgaliana** [comment]
The underlying error is:

`"openVPNPrefixIds.0.id" : "openVPNPrefix does not exists"`

It seems that the validation in the backend needs to support VPN prefixes that exist in different firewalls to be dropped in routing policies of other firewalls.

Can you check it, @soltecsis-jurios ?
