### ISSUE TITLE
In routing grids, the other firewall information disappears.

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-api#475]
When I drag and drop an OpenVPN, address, etc. from other firewall I can see the other firewall in brackets:
<img width="1373" alt="Captura de pantalla 2021-09-14 a las 9 01 56" src="https://user-images.githubusercontent.com/28894874/133210717-71e2591e-0571-41eb-b0bb-652ef80c4393.png">

But If I reload the grid the in brackets info desappears:
<img width="1052" alt="Captura de pantalla 2021-09-14 a las 9 03 32" src="https://user-images.githubusercontent.com/28894874/133210924-86e6d9ab-68d5-4bac-a53f-c22c65099148.png">

**Comment by fperezgaliana** [comment]
The UI needs to receive the following fields to show the required information:

- `cluster_id` / `cluster_name` if the object belongs to another cluster
- `firewall_id` / `firewall_name`
- `host_id` / `host_name`

Once that the grid calls are modified to add them, the data will be shown automatically.

**Comment by cmunyoz** [comment]
Ok, I'll modify the information returned for the routing rules and routes grids, and include the missing data.
