### ISSUE TITLE
It is possible to add empty hosts when creating a new routing rule.

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-api#476]
In the creation process for a new routing rule, we can use an empty host (without any IP address):
<img width="1440" alt="Captura de pantalla 2021-09-14 a las 9 50 04" src="https://user-images.githubusercontent.com/28894874/133217654-f63be2c5-0428-4416-8ce0-f7871a5dd299.png">

This is not correct, we can not use an empty host in any position.

In fact, the API responds with error:
<img width="1257" alt="Captura de pantalla 2021-09-14 a las 9 49 37" src="https://user-images.githubusercontent.com/28894874/133217575-15ae51c4-58f2-4fb5-8ea0-0be4b7ad8232.png">

Nevertheless, the rule is created but the `From` position is empty, this a bug in the API because a routing rule with empty `From` position should not be created:
<img width="1196" alt="Captura de pantalla 2021-09-14 a las 9 48 51" src="https://user-images.githubusercontent.com/28894874/133217438-94d7b663-2d50-4764-beca-44402dded0da.png">

- [x] Add a new restriction in the API for avoid the creation of routing rules with empty `From` position.
- [x] The UI should not allow add empty hosts in the routing rule creation procedure.

**Comment by fperezgaliana** [comment]
Added new restriction to manage the empty group/host case:

![imagen](https://user-images.githubusercontent.com/28951240/133403032-51747e88-1d20-49d1-b81a-6b286adb3e4d.png)
