### ISSUE TITLE
Allow adding groups in the routing rule creation procedure.

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-api#477]
At this moment it is not possible to add IP objects groups in the routing rule creation procedure. 
Modify the UI for allow it, but controlling that the group is not an empty group (without items).

**Comment by fperezgaliana** [comment]
I've fixed a bug that prevented to add object groups when creating the routing rules.

Also, I've added a case in the error parser to manage the empty groups. Now, when this error is received, the UI will show the appropriate message:

![imagen](https://user-images.githubusercontent.com/28951240/133240281-5445ecda-b858-4c7b-a69b-1c2b17fcc1a8.png)
