### ISSUE TITLE
Adding/removing IPs from host doesn't update flags of firewalls.

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-api#478]
If I add or remove an IP from a host that is being used in the policy, routing policy or routes of a firewall/cluster, the compilation/installation flags of the firewalls in which the host is being used are not updated. 

If I reload the firewalls/clusters tree the flags are updated, then the problem is that the UI is not refreshing the flags right.

The same happens when the host is part of a group that is being used in a policy, route or routing policy.

**Comment by fperezgaliana** [comment]
The UI wasn't using the `fw_status` return data for these cases.
