### ISSUE TITLE
Changing the name of an OpenVPN Prefix don't change the name of the groups that use it.

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-api#479]
If we change the name of an OpenVPN Prefix that is being used into a group, in the Objects tree, under the group that contains the prefix, the name of the prefix doesn't changes.

In the next screenshot we can see that I have changed the prefix name from SOLTECSIS to SOLT, but the node under the group has still the name SOLTECSIS:
<img width="781" alt="Captura de pantalla 2021-09-14 a las 10 21 36" src="https://user-images.githubusercontent.com/28894874/133222431-6050df27-3482-4e15-b7f8-3591a3612f5b.png">

I the tree is repaired the problem is solved.

- [x] The API must rename the nodes under groups using the Prefix.
- [x] The UI must update the information in the objects tree.

**Comment by fperezgaliana** [comment]
The objects tree is updated to reflect the changes. Also, if you modify a prefix and the group panel is open, it will be reloaded.
