### ISSUE TITLE
Don't allow deletion of a routing table that is in use.

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-api#480]
UI allows the remove of a routing table that is being used in a routing policy. The API returns error if we continue with the removal.

Only allow deletion of routing tables that are not being used in any routing policy.

**Comment by fperezgaliana** [comment]
We need a new API call to check where is used a routing table, so the UI can show a restrictions message in the same way that it's displayed when trying to delete an object.

We need to follow the same behavior than any of the existing `restricted` calls (f.i. `/ipobj/restricted`). Also, if a new restriction name is added, I need to know its name to manage it in the UI.

**Comment by fperezgaliana** [comment]
We need to change the new restrictions call to follow the same behavior of the existing:

- [ ] Change the endpoint from `restrictions` to `restricted`
- [ ] If the routing table hasn't any restrictions, it should return a `204` response (no content)
- [ ] If it has restrictions, it should return a `403` response with the following structure as the `data`:

```
{
  restrictions: {
    routingTableUsedInRule: [ ] 
  }
}
```

**Comment by cmunyoz** [comment]
When I try to delete a routing table not in use, I get the next error:
<img width="1279" alt="Captura de pantalla 2021-09-16 a las 16 43 45" src="https://user-images.githubusercontent.com/28894874/133633167-9f7298a8-73f8-462c-a3ec-83c1148e51c0.png">

**Comment by fperezgaliana** [comment]
The UI was using the wrong API call, now it's fixed.
