### ISSUE TITLE
Mark data modification doesn't modify flags of firewalls that uses it.

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-api#481]
If I change the code or name of a firewall mark that is being used in a policy rule or routing rule, the compilation/installation flags of the firewall/cluster using it are not updated.

- [x] Adding a mark to a firewall policy rule doesn't modify the flags (API and UI).
- [x] Removing a mark from a firewall policy rule doesn't modify the flags (API and UI).
- [x] Adding a mark to a routing rule doesn't alter the flags (only UI, if I reload the tree the flags are updated).
- [x] Modify the information of a firewall mark used in a firewall policy doesn't change the flags (API and UI).
- [x] Modify the information of a firewall mark used in a routing rule doesn't change the flags (API and UI).

**Comment by soltecsis-jurios** [comment]
API changes have been implemented.

**Comment by fperezgaliana** [comment]
The first 3 cases work as expected.

For the last 2 cases, I see that the call to update the mark doesn't return a ' fw_status'  field with the affected clusters/firewalls, as all the other calls do. For example, updating an object  returns:

![imagen](https://user-images.githubusercontent.com/28951240/133415878-aca171f8-dec4-4826-8d0d-c75a5e401597.png)

Once the API returns this information, the firewalls tree will be updated automatically.

**Comment by fperezgaliana** [comment]
With the new version of the API and the changes done in the UI, everything is working.
