### ISSUE TITLE
Firewall/cluster deletion restrictions don't take into account routing data.

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-api#487]
If we try to remove a firewall/cluster who's items (IPs, OpenVPN and Prefixes) are being used in a route or routing rule of any other firewall, the delete restrictions should warn us about it and don't allow continue with the deletion.

**Comment by fperezgaliana** [comment]
Added new restrictions and fixed a bug in the restrictions component that showed "undefined" on some of them.

**Comment by cmunyoz** [comment]
If a firewall object (interface IP, OpenVPN or Prefix) is used in a firewall policy, when I try to delete the firewall the deletion restrictions windows arises. If I double click over the restriction row it brings me to the policy rule with the restriction. If then I remove the firewall object from the rule, then the restrictions window appears and updates the restrictions status.

This is a great behavior because I can navigate across all the restrictions solving them until I can remove the firewall.
 
When I have restrictions related with firewall objects being used in other firewalls routes or routing rules, this behavior doesn't go. I can double clic over the restriction and it brings me to the route or routing rule, but if I remove the firewall object, the restrictions window doesn't maximizes and doesn't update its content automatically.

**Comment by fperezgaliana** [comment]
The UI had a bug that didn't reload the restrictions panel if the deleted object  was OpenVPN related. Now it's fixed.

**Comment by fperezgaliana** [comment]
Added the reloading of the restrictions when modifying the gateway of a route. Added a button to update manually the restrictions.
