### ISSUE TITLE
Detect FWCloud-Agent communication errors.

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-api#517]
Instead of a general communication error, FWCloud-API should return a concrete error for these scenarios:

- [x] If the TCP port doesn't responds. We can reproduce it easily indicating a TCP port where no process is listening.
```2021-10-15 09:55:46|ERROR|Error getting network interface information: {"message":"connect ECONNREFUSED 192.168.56.108:33034","name":"Error","stack":"Error: connect ECONNREFUSED 192.168.56.108:33034\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)\n    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:129:14)","config":{"url":"https://192.168.56.108:33034/api/v1/interfaces/info","method":"get","headers":{"Accept":"application/json, text/plain, */*","X-API-Key":"dsfdsafasfasfasdfa","User-Agent":"axios/0.21.4"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}},"code":"ECONNREFUSED"}```

- [x] If the IP is not in use. We will get a timeout in the communication.
```2021-10-15 09:57:56|ERROR|Error getting network interface information: {"message":"connect ETIMEDOUT 192.168.56.109:33034","name":"Error","stack":"Error: connect ETIMEDOUT 192.168.56.109:33034\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)\n    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:129:14)","config":{"url":"https://192.168.56.109:33034/api/v1/interfaces/info","method":"get","headers":{"Accept":"application/json, text/plain, */*","X-API-Key":"dsfdsafasfasfasdfa","User-Agent":"axios/0.21.4"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}},"code":"ETIMEDOUT"}```

- [x] If the supplied API Key is incorrect, the API must notify the UI about it and the UI will print the corresponding error message.

- [x] If the communication protocol is incorrect. We use HTTP when the agent expects HTTPS communications or viceversa.
```2021-10-15 10:08:53|ERROR|Error getting network interface information: {"message":"read ECONNRESET","name":"Error","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)\n    at TCP.callbackTrampoline (internal/async_hooks.js:129:14)","config":{"url":"http://192.168.56.108:33033/api/v1/interfaces/info","method":"get","headers":{"Accept":"application/json, text/plain, */*","X-API-Key":"dsfdsafasfasfasdfa","User-Agent":"axios/0.21.4"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}},"code":"ECONNRESET"}```

**Comment by fperezgaliana** [comment]
I've added support for the errors, with the following messages:

```
"ECONNREFUSED": "Refused connection",
"ETIMEDOUT": "Response time exceeded",
"ECONNRESET": "Connection has been reset",
```
