### ISSUE TITLE
Docker compatibility

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-api#541]
The best option is to disable the IPTables support in Docker and manage the firewall policy by means of FWCloud:
https://github.com/moby/moby/issues/28241

- [x] Option in the firewall/cluster options tab for enable/disable Docker compatibility.
- [x] If this option is enabled, the FWCloud compiler will include code in the FWCloud policy load script for check that the Docker IPTables support is disabled.
- [x] New documentation section (FWClou & Docker) in the FWCloud website in which we explain how disable de IPTables support in Docker and how add rules in FWCloud for manage Docker communications using as example a server running two Docker instances.
- [x] When the user enables docker support for a firewall, an information window will arise referencing the documentation that we have described in the previos parraf.

Information about the IPTables rules created by Docker:
https://forums.docker.com/t/understanding-iptables-rules-added-by-docker/77210
https://stackoverflow.com/questions/25917941/docker-how-to-re-create-dockers-additional-iptables-rules
https://gist.github.com/x-yuri/abf90a18895c62f8d4c9e4c0f7a5c188

**Comment by sanyamason** [comment]
its a super feauture. Hopes it will be

**Comment by cmunyoz** [comment]
It will be available in the next release.
