### ISSUE TITLE
New calls to display and download policy script

### ISSUE THREAD

**Issue by soltecsis-jurios** [soltecsis/fwcloud-api#586]
In order to implement soltecsis/fwcloud-ui-src#623, two new calls are necessary:

- An api call which returns the script content (might be necessary compile it first)
- An api call which download the script file (might be necessary compile it first also)

**Comment by cmunyoz** [comment]
If the pending compilation flag is active, then FWCloud-UI should show a message requesting firewall/cluster compilation before executing the requested action.
