### ISSUE TITLE
Custom default policy (template)? Howto/roadmap?

### ISSUE THREAD

**Issue by tolgaulas** [soltecsis/fwcloud-api#889]
Hello, is there a roadmap/way to hack to (re?)define the default policy? We like to deploy many hosts, and one by one rule definition can be time consuming without a default policy.. 

Thanks in advance.

**Comment by cmunyoz** [comment]
Hi, it is possible to create a template firewall/cluster with the default policy that you need and then create a new firewall/cluster cloning such template:
<img width="490" alt="Captura de pantalla 2024-12-16 a las 9 16 02" src="https://github.com/user-attachments/assets/04925442-fbac-4365-8f24-a309cc8bd6a8" />

Is this what you need?
Thanks.
